services:
  postgres:
    image: postgres:16
    container_name: film_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac
      POSTGRES_DB: prac
    ports:
      - "5433:5432"
